# Generated by Django 4.0 on 2022-06-12 16:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Server_Os',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='SSL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(choices=[('1', ''), ('Deposit Issue(Add Balance Issue)', 'Deposit Issue(Add Balance Issue)'), ('Bad Item/Order', 'Bad Item/Order'), ('Report Issue', 'Report Issue'), ('ArzijShop Account Issue', 'ArzijShop Account Issue'), ('Apply for a Seller', 'Apply for a Seller'), ('Other', 'Other')], default='1', max_length=50, verbose_name='What can help you with?')),
                ('description', models.TextField(verbose_name='Description')),
                ('status', models.CharField(choices=[('Unacceptable', 'Unacceptable'), ('Acceptable', 'Acceptable'), ('Pending', 'Pending')], default='Pending', max_length=50)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateField(auto_now_add=True)),
                ('added_by_seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.newuser')),
            ],
        ),
        migrations.CreateModel(
            name='Product_ssh',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, unique=True)),
                ('country', models.CharField(choices=[('RUS', 'Russia'), ('USA', 'USA'), ('GER', 'Germany')], default='RUS', max_length=3)),
                ('tld', models.CharField(help_text='Add Your Domain', max_length=20)),
                ('detected_hosting', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('added_on', models.DateTimeField(auto_now_add=True)),
                ('stripe_product_id', models.CharField(max_length=100)),
                ('added_by_seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.newuser')),
                ('ssl', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.ssl')),
            ],
        ),
        migrations.CreateModel(
            name='Product_Smtp',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, unique=True)),
                ('country', models.CharField(choices=[('RUS', 'Russia'), ('USA', 'USA'), ('GER', 'Germany')], default='RUS', max_length=3)),
                ('webmail', models.CharField(choices=[('YES', 'YES'), ('NO', 'NO')], default='YES', max_length=3)),
                ('detected_hosting', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('added_on', models.DateTimeField(auto_now_add=True)),
                ('stripe_product_id', models.CharField(max_length=100)),
                ('added_by_seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.newuser')),
            ],
        ),
        migrations.CreateModel(
            name='Product_Shell',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, unique=True)),
                ('country', models.CharField(choices=[('RUS', 'Russia'), ('USA', 'USA'), ('GER', 'Germany')], default='RUS', max_length=3)),
                ('tld', models.CharField(help_text='Add Your Domain', max_length=20)),
                ('server_information', models.TextField(max_length=500)),
                ('detected_hosting', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('added_on', models.DateTimeField(auto_now_add=True)),
                ('stripe_product_id', models.CharField(max_length=100)),
                ('added_by_seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.newuser')),
                ('server_os', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.server_os')),
                ('ssl', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.ssl')),
            ],
        ),
        migrations.CreateModel(
            name='Product_Rdp',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, unique=True)),
                ('country', models.CharField(choices=[('RUS', 'Russia'), ('USA', 'USA'), ('GER', 'Germany')], default='RUS', max_length=3)),
                ('state', models.CharField(help_text='Add Your state', max_length=20)),
                ('windows', models.IntegerField()),
                ('ram', models.CharField(max_length=50)),
                ('Access', models.CharField(default=1, max_length=100)),
                ('detected_hosting', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('added_on', models.DateTimeField(auto_now_add=True)),
                ('stripe_product_id', models.CharField(max_length=100)),
                ('status_field', models.CharField(blank=True, choices=[('POSTED', 'POSTED'), ('HANGING', 'HANGING')], default='HANGING', max_length=10, null=True)),
                ('added_by_seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.newuser')),
            ],
        ),
        migrations.CreateModel(
            name='Product_Mailer',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, unique=True)),
                ('country', models.CharField(choices=[('RUS', 'Russia'), ('USA', 'USA'), ('GER', 'Germany')], default='RUS', max_length=3)),
                ('detected_hosting', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('added_on', models.DateTimeField(auto_now_add=True)),
                ('stripe_product_id', models.CharField(max_length=100)),
                ('added_by_seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.newuser')),
            ],
        ),
        migrations.CreateModel(
            name='Product_Leads',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, unique=True)),
                ('country', models.CharField(choices=[('RUS', 'Russia'), ('USA', 'USA'), ('GER', 'Germany')], default='RUS', max_length=3)),
                ('source', models.TextField(max_length=1000)),
                ('Email_Domains', models.CharField(help_text='Add Your Domain Email', max_length=30)),
                ('email_num', models.CharField(help_text='Add Number of Your Emails', max_length=5)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('added_on', models.DateTimeField(auto_now_add=True)),
                ('stripe_product_id', models.CharField(max_length=100)),
                ('added_by_seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.newuser')),
            ],
        ),
        migrations.CreateModel(
            name='Product_cPanel',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, unique=True)),
                ('country', models.CharField(choices=[('RUS', 'Russia'), ('USA', 'USA'), ('GER', 'Germany')], default='RUS', max_length=3)),
                ('tld', models.CharField(help_text='Add Your Domain', max_length=20)),
                ('detected_hosting', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('added_on', models.DateTimeField(auto_now_add=True)),
                ('stripe_product_id', models.CharField(max_length=100)),
                ('added_by_seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.newuser')),
                ('ssl', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.ssl')),
            ],
        ),
        migrations.CreateModel(
            name='PriceSsh',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_price_id', models.CharField(max_length=100)),
                ('price', models.IntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.product_ssh')),
            ],
        ),
        migrations.CreateModel(
            name='PriceSmtp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_price_id', models.CharField(max_length=100)),
                ('price', models.IntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.product_smtp')),
            ],
        ),
        migrations.CreateModel(
            name='PriceShell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_price_id', models.CharField(max_length=100)),
                ('price', models.IntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.product_shell')),
            ],
        ),
        migrations.CreateModel(
            name='PriceRdp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_price_id', models.CharField(max_length=100)),
                ('price', models.IntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.product_rdp')),
            ],
        ),
        migrations.CreateModel(
            name='PriceMailer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_price_id', models.CharField(max_length=100)),
                ('price', models.IntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.product_mailer')),
            ],
        ),
        migrations.CreateModel(
            name='Priceleads',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_price_id', models.CharField(max_length=100)),
                ('price', models.IntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.product_leads')),
            ],
        ),
        migrations.CreateModel(
            name='PriceCpanel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_price_id', models.CharField(max_length=100)),
                ('price', models.IntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.product_cpanel')),
            ],
        ),
        migrations.CreateModel(
            name='OrderDetailSsh',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, unique=True)),
                ('customer_email', models.EmailField(max_length=255, verbose_name='Customer Email')),
                ('amount', models.IntegerField(verbose_name='Amount')),
                ('stripe_payment_intent', models.CharField(max_length=200)),
                ('has_paid', models.BooleanField(default=False, verbose_name='Payment Status')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='store.product_ssh', verbose_name='Product Ssh')),
            ],
        ),
        migrations.CreateModel(
            name='OrderDetailSmtp',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, unique=True)),
                ('customer_email', models.EmailField(max_length=255, verbose_name='Customer Email')),
                ('amount', models.IntegerField(verbose_name='Amount')),
                ('stripe_payment_intent', models.CharField(max_length=200)),
                ('has_paid', models.BooleanField(default=False, verbose_name='Payment Status')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='store.product_smtp', verbose_name='Product Smtp')),
            ],
        ),
        migrations.CreateModel(
            name='OrderDetailShell',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, unique=True)),
                ('customer_email', models.EmailField(max_length=255, verbose_name='Customer Email')),
                ('amount', models.IntegerField(verbose_name='Amount')),
                ('stripe_payment_intent', models.CharField(max_length=200)),
                ('has_paid', models.BooleanField(default=False, verbose_name='Payment Status')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='store.product_shell', verbose_name='Product Shell')),
            ],
        ),
        migrations.CreateModel(
            name='OrderDetailRdp',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, unique=True)),
                ('customer_email', models.EmailField(max_length=255, verbose_name='Customer Email')),
                ('amount', models.IntegerField(verbose_name='Amount')),
                ('stripe_payment_intent', models.CharField(max_length=200)),
                ('has_paid', models.BooleanField(default=False, verbose_name='Payment Status')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='store.product_rdp', verbose_name='Product Rdp')),
            ],
        ),
        migrations.CreateModel(
            name='OrderDetailMailer',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, unique=True)),
                ('customer_email', models.EmailField(max_length=255, verbose_name='Customer Email')),
                ('amount', models.IntegerField(verbose_name='Amount')),
                ('stripe_payment_intent', models.CharField(max_length=200)),
                ('has_paid', models.BooleanField(default=False, verbose_name='Payment Status')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='store.product_mailer', verbose_name='Product Mailer')),
            ],
        ),
        migrations.CreateModel(
            name='OrderDetailLeads',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, unique=True)),
                ('customer_email', models.EmailField(max_length=255, verbose_name='Customer Email')),
                ('amount', models.IntegerField(verbose_name='Amount')),
                ('stripe_payment_intent', models.CharField(max_length=200)),
                ('has_paid', models.BooleanField(default=False, verbose_name='Payment Status')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='store.product_leads', verbose_name='Product Leads')),
            ],
        ),
        migrations.CreateModel(
            name='OrderDetailCpanel',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, unique=True)),
                ('customer_email', models.EmailField(max_length=255, verbose_name='Customer Email')),
                ('amount', models.IntegerField(verbose_name='Amount')),
                ('stripe_payment_intent', models.CharField(max_length=200)),
                ('has_paid', models.BooleanField(default=False, verbose_name='Payment Status')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='store.product_cpanel', verbose_name='Product Cpanel')),
            ],
        ),
    ]
